#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Build') {
            node {

                echo "Descargando fuentes"
                checkout scm

                echo "Construyendo el proyecto con Gradle Wrapper"
                //sh './gradlew build -x test'

                //archive 'build/libs/*.jar'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying macht Spass.'
            }
        }
    }
}
