#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {

                echo "Checkout sources"
                //checkout scm // not working with "Build now"? -> he checkout step will checkout code from source control; scm is a special variable which instructs the checkout step to clone the specific revision which triggered this Pipeline run.

                git "https://github.com/edigonzales/ilivalidator-web-service.git/"

                //echo "Construyendo el proyecto con Gradle Wrapper"
                //sh './gradlew build -x test'

                //archive 'build/libs/*.jar'
            }
        }
        stage('Build') {
            steps {
                echo "Construyendo el proyecto con Gradle Wrapper"
                sh './gradlew build -x test'

                //archive 'build/libs/*.jar'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying macht Spass.'
            }
        }
    }
}
